### ISSUE TITLE
Deleting emails from 'Junk' folder puts it to 'Trash'

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck-webmail#10]
Deleting emails from Junk should delete it permanently without putting it to the Trash folder.
(this is how gmail also does it).

The problem is when a user gets about 20-30 SPAM a day, and mixes it into the trash, when the user manually deletes it.

**Comment by andris9** [comment]
Fixed it in the latest commit. Both messages from Junk and Trash are now deleted immediatelly, deleting from other folders moves messages to Trash.
