### ISSUE TITLE
Deleting more then 14 items do not work

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck-webmail#15]
Deleting 1,2,3...14 items works.
But 15,16, 17, 18, 19, 20 items do not.

Deleting 15 items (FAILS):

client -> server
```
_csrf | TwgHXamd-w2yzxQUkNTe0ztCMoTGiEcCIBTw
mailbox | 2b184657c4acb0049beafec6
message | 4436,4434,4433,4432,4431,4430,4429,4428,4427,4426,4425,4424,4423,4422,4421
```
Response (server -> client):
```
"/users/2b184657c4acb0049beafec5/mailboxes/2b184657c4acb0049beafdc6/messages/4436%2C4434%2C4433%2C4432%2C4431%2C4430%2C4429%2C4428%2C4427%2C4426%2C4425%2C4424%2C4423%2C4422%2C4421 does not exist"
```

Deleting 14 items (SUCCESS):

client -> server
```
_csrf | TwgHXamd-w2yzxQUkNTe0ztCMoTGiEcCIBTw
-- | --
mailbox | 2b184657c4acb0049beafec6
message | 4470,4468,4467,4466,4465,4461,4445,4444,4443,4442,4440,4439,4437,4435
```
server->client
```
success | true
mailbox | 5b184657c4acb0049beafdc8
id | […]
action | move
```
I'll try to debug this issue more this evening.

ps: deleting a single message now works. Thank you. (other report)

**Comment by bunyevacz** [comment]
Ok, this is the rout cause:
[`lib/api-client.js->_render`][0] method somehow manage to replace `,` with `%2C`.

This is the offending code:
```
 let url = path.replace(/\{([^}]+)\}/g, (match, key) => {
        if (key in args) {
            found.add(key);
            return encodeURIComponent(args[key]);
        }
        return match;
});
```

After that, url becomes: 
```
url: /users/2b184657c4acb0049beaeec5/mailboxes/2b184657c4acb0049beaeec6/messages/4475%2C4474%2C4473%2C4472%2C4471%2C4460%2C4459%2C4446%2C4441%2C4438%2C4436%2C4434%2C4433%2C4432%2C4431%2C4430%2C4429%2C4428%2C4427%2C4426
```
I need to strenghten my regexp-fu. 

I'll be back:)

[0]: https://github.com/nodemailer/wildduck-webmail/blob/master/lib/api-client.js#L326

**Comment by andris9** [comment]
Oh, that explains a lot - if I test with small UIDs then I never get this as the resulting list would be too short

**Comment by bunyevacz** [comment]
Hmm, it is not the regexp neither encodeURIComponent fault.
The url is in both case , -> %2C (which is urlencoded comma).

But it fails somewhere there.

**Comment by bunyevacz** [comment]
Found the bug. It is in `find-my-way` library, which gives 100 chars as default param length.

The code fails at
```
 // parametric route
    if (kind === NODE_TYPES.PARAM) {
      currentNode = node
      i = path.indexOf('/')
      if (i === -1) i = pathLen
      if (i > maxParamLength) return null //<--- HERE!
      decoded = fastDecode(path.slice(0, i))
      if (decoded === null) return null
      params[pindex++] = decoded
      path = path.slice(i)
      continue
}
```

And the `maxParamLength` is 100 by default:
```
  this.maxParamLength = opts.maxParamLength || 100
```

Here is a [link][0] to the current version (although we are using `1.13.0`).

The fix is rather straightforward:
In [wildduck/api.js][1] we should add a `maxParamLength` option, like this:
```
const serverOptions = {
    maxParamLength: 196,
    name: 'WildDuck API',
    strictRouting: true,
    formatters: {
        'application/json; q=0.4': (req, res, body) => {
            let data = body ? JSON.stringify(body, false, 2) + '\n' : 'null';
            res.setHeader('Content-Length', Buffer.byteLength(data));
            return data;
        }
    }
};
```
Thus overwriting the default value of 100.

While the fix may seems obvious, it is not a real fix in my opinion. It is a major design flaw in the api. 
You are converting a variable length option (HTTP PUT body) into url (HTTP PUT path). 
I think the real fix would be to have the `message` parameter inside the body, as was between the browser<->wildduck-webmail. 

The find-my-way algorithm is a recursive tree finding algoritm. It will be exponentially slower as the parameter gets longer and longer.
If you would simply keep `messages` parameter in the body, it would be a simple object key.

What is your opinion?

[0]: https://github.com/delvedor/find-my-way/blob/master/index.js#L416
[1]: https://github.com/nodemailer/wildduck/blob/master/api.js#L33

**Comment by andris9** [comment]
Yes, it seems like a bad design. I updated both wildduck and wildduck-webmail to send message list in PUT body, instead of an URL param, so the issue should be fixed in latest version.

**Comment by bunyevacz** [comment]
@andris9: 
I think it would also make sense to *explicitly* specify the max request param (as I wrote):
```
const serverOptions = {
    maxParamLength: 196,
```

Not because the `find-my-way`'s default `100` is too short, but because we be aware of this settings, 
and adjust if needed. And also to not change upstream, without our knowledge.

Thoughts?

**Comment by andris9** [comment]
Yeah, good idea https://github.com/nodemailer/wildduck/commit/50eac429658bb24d9bc61db192138cb76221f720
