### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by hansyulian** [nodemailer/wildduck-webmail#17]
I just tried the fresh installation of wildduck using the install script, then i managed to create an email account, but i have problem when trying to send the first mail. the error was:

not authorized on zone-mta to execute command { insert: "mail.chunks", ordered: true, lsid: { id: UUID("aece7256-d1f4-4af7-894a-6f51f90da84d") }, $db: "zone-mta" }

![image](https://user-images.githubusercontent.com/10959546/46077650-d9af7580-c1bb-11e8-9d8d-c285d65e3d5e.png)

Any idea for this?

**Comment by hansyulian** [comment]
I found it, it's the dbs.toml configuration, all fine now

**Comment by andris9** [comment]
was the faulty config generated by install script or did you change something yourself?

**Comment by hansyulian** [comment]
no, it would be fine if the mongodb config is the default one, but in my case, i already applied authentication and change the port for mongodb, that's why the authenticated user wasn't able to access the zone-mta database, because the user was set to only be able to access the "wildduck" database

**Comment by andris9** [comment]
ok, clear
