### ISSUE TITLE
reserved username

### ISSUE THREAD

**Issue by amitsquare** [nodemailer/wildduck-webmail#2]
When i create some user name , It does show error with "reserved username" message .
If these email ids are reserved , how one can access it ?

Or how can i disable this check ?

**Comment by andris9** [comment]
Usernames are checked against a blacklist [here](https://github.com/nodemailer/wildduck-webmail/blob/c20b040f80473ab7694cec4bcf358683294efd7c/routes/account.js#L202-L205). This check only applies to the webmail app, you could create the users with any names through wildduck [API directly](http://api.wildduck.email/#api-Users-PostUser)

**Comment by ukwuezeobinna** [comment]
Is there a way to disable reserved usernames and are there services that needs to be re-started when i disable them?

**Comment by louis-lau** [comment]
You can disable it in the webmail config. You'll need to restart the webmail.

**Comment by oviliz** [comment]
For reference, as per https://github.com/nodemailer/wildduck/issues/154#issuecomment-542233751, in my case it was located in /opt/wildduck-webmail/node_modules/role-based-email-addresses/index.js
