### ISSUE TITLE
internal server error 500

### ISSUE THREAD

**Issue by W2AlharbiMe** [nodemailer/wildduck-webmail#21]
hello guys i'm trying to use react to send POST request using axios to this point /account/create
but i'm getting internal server error 500 is there any logs ?

**Comment by Weldeasy** [comment]
Hi, did you check the syslog?

Also, the api port it's configured in api.toml (check if you are sending the request to the correct port).

Hope it helps!

**Comment by W2AlharbiMe** [comment]
i solved the issue it was from redis it was not running thank you.
i used this command: 
`/etc/init.d/redis-server start`

@Weldeasy
