### ISSUE TITLE
Mails queued for delivery

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck-webmail#29]
Hello @andris9 When sending mails through wildduck webmail; it says mails are queued for delivery but it is never sent to the recipient.
And in logs it says 
![image](https://user-images.githubusercontent.com/63767821/86355918-080f8e00-bc89-11ea-941c-70f182176536.png)

**Comment by louis-lau** [comment]
Emails are inserted into mongodb so that ZoneMTA can pick them up. The ZoneMTA logs would be of more use.

**Comment by SpoortiPalakshaiah** [comment]
@louis-lau These logs are not shown up in zonemta

**Comment by louis-lau** [comment]
How do you mean?

**Comment by SpoortiPalakshaiah** [comment]
Because there is no such logs of sending mails or mails queueing up

**Comment by louis-lau** [comment]
What about the wildduck logs?

**Comment by andris9** [comment]
Do zonemta and wildduck share the same database config? Could it be that wildduck writes the message queue to one db/collection but zonemta is checking another?

**Comment by SpoortiPalakshaiah** [comment]
Zonemta and wildduck share the same configurations.

**Comment by SpoortiPalakshaiah** [comment]
We are using 2 smtp servers: haraka for inbound and zonemta for outbound. How to specify these 2 configurations in wildduck webemail?

**Comment by louis-lau** [comment]
WildDuck webmail has nothing to do with inbound smtp. It just uses the wildduck api for outbound messages. So you should look at Wildduck and ZoneMTA.

**Comment by SpoortiPalakshaiah** [comment]
So, the zonemta and wildduck should be configured in webmail's config/default.toml. Is it correct?

**Comment by louis-lau** [comment]
No. WildDuck yes, ZoneMTA no. Webmail uses the wildduck api to send messages, and wildduck stores it to mongodb for ZoneMTA to pick up.

Webmail does not directly communicate with ZoneMTA.

**Comment by SpoortiPalakshaiah** [comment]
Webmail is receiving mails correctly. But not able to send mails

**Comment by louis-lau** [comment]
I'm aware. You haven't given any further info to debug though. Take a look at the wildduck logs. Take a look at the database where outbound messages are stored (the sender config value in [dbs.toml](https://github.com/nodemailer/wildduck/blob/master/config/dbs.toml)). Show us the database configs for both wildduck and ZoneMTA. We can try to help, but unfortunately we don't have a crystal ball :grin:

**Comment by andris9** [comment]
['sender' in wildduck db config](https://github.com/nodemailer/wildduck/blob/a00be20f80ac90689d684105206f92914b882cff/config/dbs.toml#L25) must match ['sender' in zone-mta](https://github.com/zone-eu/zone-mta-template/blob/47f230b3189814f3c99194e9b2db4c5d4c609563/config/dbs-production.toml#L11), ['collection' and 'gfs' in wildduck config](https://github.com/nodemailer/wildduck/blob/a00be20f80ac90689d684105206f92914b882cff/config/sender.toml#L5-L10) must match ['collection' and 'gfs' in zone-mta](https://github.com/zone-eu/zone-mta-template/blob/47f230b3189814f3c99194e9b2db4c5d4c609563/config/queue.toml#L9-L12). Also ['zone' in wildduck config](https://github.com/nodemailer/wildduck/blob/a00be20f80ac90689d684105206f92914b882cff/config/sender.toml#L2) must exist in [zone-mta config](https://github.com/zone-eu/zone-mta-template/blob/47f230b3189814f3c99194e9b2db4c5d4c609563/config/zones/default.toml#L1).

**Comment by SpoortiPalakshaiah** [comment]
All these configurations are same.. And using this configurations I can send and receive emails correctly in Thunderbird client but not in wildduck webmail.

**Comment by louis-lau** [comment]
Smtp is different than what webmail does. It does not use smtp to communicate with ZoneMTA. Please look in to anything I suggested.

**Comment by SpoortiPalakshaiah** [comment]
I have checked with the database; the queued messages are stored there. And the `sender` in wildduck dbs.toml and zonemta dbs.toml is same;  The `collection` and `gfs` in wildduck sender.toml and zonemta queue.toml is same. 

Where can I find zone information in zonemta config? In wildduck config `zone` is set as default.

**Comment by andris9** [comment]
When sending with Thunderbird does the messages get queued to the same collection as wildduck messages or somewhere else? You can try it out by sending to a domain name thatd does not exist, this way the messag should get deferred and is not deleted from the queue.

**Comment by SpoortiPalakshaiah** [comment]
It's getting queued in different databases.

**Comment by louis-lau** [comment]
You say the configuration is the same, can you send the relevant parts of your wildduck and your ZoneMTA configuration? They can't end up in different databases if the configuration is the same.

**Comment by SpoortiPalakshaiah** [comment]
dbs.toml in wildduck
```
mongo="mongodb://<uname>:<password>@<mongodb>:27017/mails?authSource=admin"

[redis]
host="<redis>"
port=6379
db=3

sender="zone-mta"
```
dbs.toml in zonemta

```
mongo="mongodb://<username>:<password>@<mongodb>:27017/mails?authSource=admin"

# Redis connection string
redis="redis://<redis>:6379/2"

# Database name for ZoneMTA data in MongoDB. In most cases it should be the same as in the connection string
sender="zone-mta"
```

**Comment by SpoortiPalakshaiah** [comment]
I have specified database as `mails` but the queue from thunderbird is stored in `zone-mta`. And the queue from webmail is stored in `mails` itself.

**Comment by SpoortiPalakshaiah** [comment]
Hello @louis-lau and @andris9, where should I specify the database to be used for queueing of mails. 

Should I specify it in default.toml file of wildduck-webmail or dbs.toml file in wildduck.

We have a setup where wildduck, zone-mta and wildduck-webmail are all separate containers.

**Comment by louis-lau** [comment]
Should be the `sender` value as Andris noted before. In the config you sent you edited it to the correct value, but WildDuck is using another database. This means you either didn't restart wildduck, or you're not editing the right config files. Is wildduck using your configuration files?

**Comment by SpoortiPalakshaiah** [comment]
I should edit sender value in dbs.toml of wildduck container; Is it correct?

**Comment by louis-lau** [comment]
It needs to be the same as it is in ZoneMTA, see this previous reply:
https://github.com/nodemailer/wildduck-webmail/issues/29#issuecomment-652995833

**Comment by SpoortiPalakshaiah** [comment]
All these are matching.. But still the mails are queued in different database

**Comment by louis-lau** [comment]
You say you're using containers, are these docker containers or something like lxc? How have you installed wildduck?

**Comment by SpoortiPalakshaiah** [comment]
I'm using Docker containers

**Comment by louis-lau** [comment]
How are you editing the configuration?

**Comment by SpoortiPalakshaiah** [comment]
I'm editing the configuration within the container.

**Comment by louis-lau** [comment]
That's not how you should use docker, any persistent data should be added as an environment variable or as a volume, see the documentation:
https://docs.wildduck.email/#/in-depth/docker

**Comment by SpoortiPalakshaiah** [comment]
I tried by changing in volumes and still the same issue persists.

**Comment by louis-lau** [comment]
In that case I have no other suggestions ☹️ . It is working as intended for me.

**Comment by manalejandro** [comment]
Same issue here with `wildduck-webmail@latest` and `wildduck@latest`
```
wildduck    | http API 172.200.0.XXX 5d21f4e92f02ae0022145aXX [-/-] POST /users/5d21f4e92f02ae0022145aXX/submit 200 204ms
webmail     | { success: true,
webmail     |   message:
webmail     |    { id: 18,
webmail     |      mailbox: '5d21f4e92f02ae0022145aXX',
webmail     |      queueId: '1743a43347400069XX' } }
webmail     | info HTTP POST /webmail/send 302 305.453 ms - 62
wildduck    | sill IMAP [api.qvmvc2anhr6di2ys] New journal listener for 5d21f4e92f02ae0022145aXX (webmaster)
```

all seems :ok: but never outbound the :email: i have to resend it by IMAP and all is :+1:

**Comment by manalejandro** [comment]
Sorry was a missconfiguration in my wildduck, had "zone-mta" instead "default" zone, thanks
