### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by laurivosandi** [nodemailer/wildduck-webmail#34]
Hi, could you also publish image at Docker Hub along with docker-compose.yml example?

I was expecting to find something at https://hub.docker.com/r/nodemailer/wildduck-webmail

**Comment by louis-lau** [comment]
I've published the docker image. I may look into adding an example docker-compose in the future, or you could be so kind as to contribute one 😁

**Comment by louis-lau** [comment]
Also, since this project doesn't seem to have any tagged releases, only `latest` is available on docker hub.

**Comment by andris9** [comment]
@laurivosandi see veebimeili projekt on enamvähem surnud. Sain Zonest mõnda aega tagasi kinnituse, et nad teevad oma arenduses oleva veebimeili avalikuks samadel timgimustel nagu muu WildDuck projekt. Praegu saab seda proovida webmail.ee aadressil (peab olema Zone virtuaalserver koos emaili kontoga), Githubis kood kõik olemas, aga private repo. Kui see lahti tehakse, siis panen selle siin üldse kinni.
