### ISSUE TITLE
Dockerfile --config not found

### ISSUE THREAD

**Issue by pradyparanjpe** [nodemailer/wildduck-webmail#36]
# Background
I'm running a podman pod with wildduck-webmail as a contianer named `webmail`
(alongside wildduck, redis, mongo, which are up and running)

# Error:

`webmail` container exits with error logged as:

```$ podman logs webmail```

## Output:
`Error: ["/etc/wildduck/www.toml"] "/etc/wildduck/www.toml": ENOENT: no such file or directory, open '"/etc/wildduck/www.toml"'`

# It Exists:
I can access /etc/wildduck/www.toml using

```$ podman exec -it ls /etc/wildduck/www.toml```

## Output:
/etc/wildduck/www.conf

(it does exist)

**Comment by pradyparanjpe** [comment]
# Workaround:

added to my container-compose.yml (docker-compose.yml)

`entrypoint: ["node", "server.js", "--config=/etc/wildduck/www.toml"]`

**Comment by laurivosandi** [comment]
This was due to buggy Dockerfile that was fixed with https://github.com/nodemailer/wildduck-webmail/commit/2a944292dd6e61706fa7230ed1423814c273bdbc
