### ISSUE TITLE
ability to remove unused accounts

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck-webmail#38]
Hello,
I wanted to know if there is a way to delete the accounts of users who do not connect to the mailbox for a long time

**Comment by laurivosandi** [comment]
This is definitely out of scope of webmail, and I doubt whether it would even make sense for https://github.com/nodemailer/wildduck

Such account lifecycle management is usually handled by IAM software. Alternatively you can roll your own cronjob that purges accounts using Wildduck API https://docs.wildduck.email/api/#operation/deleteUser
