### ISSUE TITLE
its not open at external browser

### ISSUE THREAD

**Issue by martandya** [nodemailer/wildduck-webmail#4]
successfully installed but link not working at external browser ....
So how can i change config so it can be open in any external browser ?
Where i need to change config so it can be open http://example.com ?

**Comment by bunyevacz** [comment]
You need a reverse proxy (nginx) in front of wildduck.
Wildduck is by default run on port `8080`, and not on `80`. 
I would advise for reverse proxy, so you can have other internal websites working together behind a reverse proxy. 

@andris9: I think this bugreport can be closed.
