### ISSUE TITLE
User-Helpscreen shows wrong email address - attached is the updated template file

### ISSUE THREAD

**Issue by ymir1v** [nodemailer/wildduck-webmail#42]
The helpscreen of the user shows a wrong email address "username@maildomain@servicedomain" in all three categories "IMAP, PO3 and SMTP"

Note:
All useraccounts we used in our tests were created using curl and not the "create account" web interface functionality - since the web interface ignores the mail domain as part of the username so it is not possible to create multiple users with the same name but different mail domains.

for us this fixes the issue:

in "/opt/wildduck-webmail/views"
file "help.hbs"

change:
```
            {{#if user}}
            <tr>
                <th>
                    E-mail address
                </th>
                <td>
                    {{user.username}}@{{serviceDomain}}
                </td>
                <td>
                    {{user.username}}@{{serviceDomain}}
                </td>
                <td>
                    {{user.username}}@{{serviceDomain}}
                </td>
            </tr>

```

to:
```
            {{#if user}}
            <tr>
                <th>
                    E-mail address
                </th>
                <td>
                    {{user.address}}
                </td>
                <td>
                    {{user.address}}
                </td>
                <td>
                    {{user.address}}
                </td>
            </tr>
```
[help.zip](https://github.com/nodemailer/wildduck-webmail/files/6716120/help.zip)

**Comment by louis-lau** [comment]
@ymir1v Please create a pull request with your changes, instead of a zip attached to an issue.
