### ISSUE TITLE
block automatic account creation

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck-webmail#48]
Hi,
I have the problem that I find many fake accounts created automatically.
I enabled the captcha and cloudflare side protections, but anyway they are created.

there is another way to block the creation of fake users.

**Comment by andris9** [comment]
You can disable account creation by setting `allowJoin` to `false` [here](https://github.com/nodemailer/wildduck-webmail/blob/master/config/default.toml#L14)

**Comment by Bianconiglio** [comment]
hello, thanks for the answer, I'm fine that users are created, but not automatically that is every 5-10 sec a user created and of the type myname01, myname02 ....

**Comment by andris9** [comment]
You can enable reCAPTCHA v3 to defend against bots. You need to register [reCAPTCHA v3 keys](https://www.google.com/recaptcha/admin/create) and add this [here](https://github.com/nodemailer/wildduck-webmail/blob/master/config/default.toml#L48)

**Comment by Bianconiglio** [comment]
yes i did i enabled recaptcha v3 and i have enable cloudflare check for bot.

there is a system to block through nginx the number of requests on the registration page type 1 per hour from the same ip. I have seen that nginx has limit.

limit_req_zone $binary_remote_addr zone=one:10m rate=1r/m;

 location /account/create {
                limit_req zone=one burst=5 nodelay;
    }

**Comment by andris9** [comment]
Well, yeah, fake users are a big problem. That account creation form is there as a demo. In a real system, you should probably have your own account signup form and you'd create the user accounts via API calls.

**Comment by Bianconiglio** [comment]
you're right, a big problem
