### ISSUE TITLE
Alias address for info

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck-webmail#49]
Hello,
how can i create an alias for the user info?.
I know that the info user is reserved and I initially created info @ mydomain1 and it works fine with his mailbox.

now I would like to create an alias of info @ mydomain2 on info @ mydomain1 from the web interface I can't because info is reserved I should create it from the API.

Can anyone help me on which command to run?

**Comment by louis-lau** [comment]
Yes, you can use the wildduck API directly, or you ca turn off special name blocking in the webmail:
https://github.com/nodemailer/wildduck-webmail/blob/3371984a32a7942d7859c3fcde923cf62484e7fa/config/default.toml#L15

For calling the wildduck API you can use any http client you're comfortable with. A cli application like `curl` or a GUI like Postman for example.

**Comment by Bianconiglio** [comment]
Hi 
thanks for the answer curl is perfect but which API string should I refer to?

 curl -i -XPOST http://localhost:8080/domainaliases \ ??

**Comment by louis-lau** [comment]
If you want all addresses of that domain aliased then yes, that's the endpoint. If you only want to add an alias for this user then you can create an additional address for the user (this is what wildduck-webmail does when creating an alias): https://docs.wildduck.email/api/#operation/createUserAddress

**Comment by Bianconiglio** [comment]
thanks a lot I managed to do it
