### ISSUE TITLE
Webmail doesn't start by docker-compose 

### ISSUE THREAD

**Issue by alternativshik** [nodemailer/wildduck-webmail#57]
I'm trying to deploy by https://github.com/nodemailer/wildduck-dockerized and have this issue

wildduck-webmail_1  | info Express WWW server listening on port 3000
wildduck-webmail_1  | /app/node_modules/ioredis/built/Command.js:43
wildduck-webmail_1  |         this.args = args.flat();
wildduck-webmail_1  |                          ^
wildduck-webmail_1  |
wildduck-webmail_1  | TypeError: args.flat is not a function
wildduck-webmail_1  |     at new Command (/app/node_modules/ioredis/built/Command.js:43:26)
wildduck-webmail_1  |     at EventEmitter.select (/app/node_modules/ioredis/built/utils/Commander.js:92:13)
wildduck-webmail_1  |     at Socket.<anonymous> (/app/node_modules/ioredis/built/redis/event_handler.js:40:18)
wildduck-webmail_1  |     at Object.onceWrapper (events.js:286:20)
wildduck-webmail_1  |     at Socket.emit (events.js:203:15)
wildduck-webmail_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:10)
root_wildduck-webmail_1 exited with code 1

**Comment by sihruabby** [comment]
same issue here

**Comment by Anyman552** [comment]
Same issue here. The problem could be caused by an outdated Node version. Alpine 3.9 uses Node 10, where the problem seems to occur.

**Comment by Lauri-L** [comment]
Seems to be so. I built the wildduck-webmail container locally, bumping the versions in Dockerfile to alpine:3.18 and python3 and got it at least running. Don't know if it breaks anything else though.

**Comment by dmascord** [comment]
As per Lauri-L, I reached the same conclusion:

```
diff --git a/Dockerfile b/Dockerfile
index 0d87511..99e60c2 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,5 @@
 # ---
-from alpine:3.9 as builder
+from alpine:3.18 as builder
 
 ARG UID=1000
 ENV APP_PATH /app
@@ -10,13 +10,13 @@ RUN chown -R builder .
 
 RUN apk add --no-cache nodejs
 RUN apk add --no-cache openssl
-RUN apk add --no-cache --virtual build-deps git python npm make g++
+RUN apk add --no-cache --virtual build-deps git python3 npm make g++
 
 USER builder
 RUN npm install && npm run bowerdeps
 
 # ---
-from alpine:3.9 as app
+from alpine:3.18 as app
 RUN apk add --no-cache nodejs
 ENV APP_PATH /app
 WORKDIR ${APP_PATH}

```

**Comment by bramhoven** [comment]
I created a PR for the changes mentioned by @Lauri-L and @dmascord. Hopefully it will get the docker image back up and running!

**Comment by laurivosandi** [comment]
Looks like this issue is closed for now
