### ISSUE TITLE
admin page

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck-webmail#9]
Creating users without any form of authentication and on the fron page seems like a bad idea to me.
And a major showstopper to host the webmail to the wider web.

Thinking through, there should be an admin page. 
At first run, when there is no user in the system, it should let to create a fixed user, eg.
`info@amazeme.com`.

Then this user would become an admin user, and allowed to add new users to the system.
Also allowed to add aliases to the user (currently any user can assign any email address to himself, which is a major no-no).
Delete user, adjust quotas of each user, etc.

What do you think? Or is it something obvious I'm missing here?

**Comment by bunyevacz** [comment]
What I have done at the moment:
I have put behind a nginx reverse proxy the whole wildduck setup (created with install.sh inside a kvm virtual machine). 
The nginx reverse proxy requires http basic auth.
I added the 'mail.company.com' dns name into the inside dns server (dnsmasq), so if you are inside the company network, you directly access the wildduck webmail. 
If you are outside the company network (from the internet) it requires an additional http basic authentication.

I disabled from the outside http, only allow https. I also turned on 2fa auth for each user, and generated app passwords for outlook. (app password page shows the password with space, so simple copy-paste is not possible. And cause major headache for the first time, why it can not log in:-\).

So I believe I secured (turtle shell security:) the webmail well enough for prime time.
So the company started using it, mailboxes vary between 1-36GiB/user. Data is moved from the old system via outlook (export to .pst file, open in the new account and drag&drop to the mail account).
So it synchronize it via IMAP-SSL.

In this setup I think some admin page (be it an outside project, or a subproject of wildduck-webmail) would be highly beneficial. 
One for user management, one for statistics.  Or be it one central account. I do not care, but there are people who like to see graphs... :)

The question is where to create user handling web software, and where to create the statistics. 
I will definietly help with testing, as I already use your software. Maybe I even can help you a little with the actual programing. Just need to figure out what is the best path forward. 
Thoughts?

**Comment by andris9** [comment]
Regarding admin page, building one is currently out of scope (which mostly means that I don't have time for it) but all operations can be managed using simple HTTP based [API](http://api.wildduck.email/), so building a custom admin page on top of it should be fairly easy to do.

Also, it is interesting you say that spaces for app specific passwords are an issue, for example I can authenticate using a copypasted password that has all the spaces:

![screen shot 2018-06-14 at 10 59 06](https://user-images.githubusercontent.com/132242/41399106-1c763a44-6fc2-11e8-95fa-aff99caa3e66.png)

**Comment by andris9** [comment]
Yes, spaces are internally removed from app specific passwords (16 random letters) but not from regular passwords

**Comment by andris9** [comment]
The actual logic goes like this:
1. Provided password is tried against user master password as is, so if you have a trailing space in the password etc. it is not removed
2. If password did not match then all whitespace is removed and if the resulting password length is 16 and it only contains latin letters then it is compared agains app specific passwords
3. If still no match then the login is considered as failed

**Comment by bunyevacz** [comment]
Still, would a pull request welcome to show app specific password as it were with spaces, but 
when copied only copies the actual password (without spaces) ?
I'm thinking to this solution:
http://jsfiddle.net/pc3ytv27/1/

it is displayed as `upeg useu pcgx xfrb`, but when you copy
it copies without spaces: `upeguseupcgxxfrb`

It is pure CSS solution.

**Comment by andris9** [comment]
Sure, why not. Gmail also does not seem to include actual whitespace but uses CSS padding to separate text blocks

![screen shot 2018-06-14 at 12 33 16](https://user-images.githubusercontent.com/132242/41404259-66b6b806-6fcf-11e8-93ab-273663306a4d.png)

**Comment by andris9** [comment]
I tested the css fiddle and it did not seem too reliable, as it expects the browser to render characters in specific length, otherwise the columns are not split correctly. So spliiting the password in the server and displaying it as 4 span elements with padding seems a better approach.

**Comment by bunyevacz** [comment]
I try to submerge into the server side. I hope I can do it by myself.

**Comment by Lyamc** [comment]
Having an admin page would be nice, preferably a default one with an admin or postmaster@domain.xyz

Some things that could be done with admin web page

- Allow users to create accounts by manual approval
- Enforce password security such as a forced password reset
- Deletion of users
- Modify encryption strength/type, etc

etc

I gotta say, I'm really impressed with how quickly I was able to get this up and running! Well done.

**Comment by louis-lau** [comment]
@Lyamc Since this issue was opened the're now multiple third party admin UI's available:
https://docs.wildduck.email/#/additional-software/third-party-projects

**Comment by Jordan-Hall** [comment]
> @Lyamc Since this issue was opened there's now multiple third party admin UI's available: https://docs.wildduck.email/#/additional-software/third-party-projects

3rd party admin panel is actually broken. the API folder appears to be missing

**Comment by laurivosandi** [comment]
Most of the stuff that is discussed here should be addressed by IAM setup. Do not reinvent stuff in webmail that ought to be elsewhere. There are now plenty of projects that address this such as Authelia, Pomerium, Keycloak and others.

Style example here: https://git.k-space.ee/k-space/kube/src/branch/master/wildduck/webmail.yaml#L38
